# yaml-language-server: $schema=https://docs.mergify.com/mergify-configuration-schema.json

queue_rules:
  - name: default
    merge_conditions:
      - check-success=nix-flake-check
pull_request_rules:
  - name: Automerge PRs using the merge queue
    conditions:
      - label=merge-queue
      - base=main
    actions:
      queue:
        name: default
  - name: Delete head branch after merge
    conditions:
      - merged
    actions:
      delete_head_branch: {}
