# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: "Nix Flake Inputs Update"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 10 * * 0" # https://crontab.guru/#0_10_*_*_0

jobs:
  update-flake-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v30
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update flake inputs
        id: update
        uses: DeterminateSystems/update-flake-lock@v24
        with:
          pr-title: "chore: update flake.lock"
          commit-msg: "chore: update flake.lock"
          pr-labels: |
            dependencies
            automated
            merge-queue

      - name: Print PR number
        run: |
          echo Pull request number is ${{ steps.update.outputs.pull-request-number }}.
